import { readFileSync, writeFileSync } from "node:fs"
import path from "node:path"

import { REPO } from "@studio/lib/paths"

/*
 * Edits clubs/registry.ts, the one list of served clubs: `import x from "./slug"` and `[…, x]`.
 */

const REGISTRY = path.join(REPO, "clubs", "registry.ts")

/** `809-social-club` → `club809SocialClub`; `naho` → `naho`. */
export function identifierOf(slug: string): string {
  const camel = slug.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase())
  return /^[0-9]/.test(camel) ? `club${camel.charAt(0).toUpperCase()}${camel.slice(1)}` : camel
}

export function registerClub(slug: string, source = readFileSync(REGISTRY, "utf8")): string {
  if (new RegExp(`from "\\./${slug}"`).test(source)) return source
  const id = identifierOf(slug)
  const imports = [...source.matchAll(/^import (\w+) from "\.\/([\w-]+)"$/gm)]
  if (imports.length === 0) throw new Error("clubs/registry.ts: no club import found")
  const lines = [...imports.map((m) => ({ id: m[1], slug: m[2] })), { id, slug }].sort((a, b) =>
    a.slug.localeCompare(b.slug),
  )
  const block = lines.map((l) => `import ${l.id} from "./${l.slug}"`).join("\n")
  const start = imports[0].index!
  const last = imports.at(-1)!
  const end = last.index! + last[0].length
  let next = source.slice(0, start) + block + source.slice(end)
  next = next.replace(/= \[([^\]]*)\]/, (_, list: string) => {
    const ids = list
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean)
    return `= [${[...ids, id].join(", ")}]`
  })
  return next
}

export function writeRegistration(slug: string): boolean {
  const before = readFileSync(REGISTRY, "utf8")
  const after = registerClub(slug, before)
  if (after !== before) writeFileSync(REGISTRY, after)
  return after !== before
}

/** clubs/<slug>/index.ts of a generated club. */
export function clubIndexSource(name: string, city: string): string {
  return `import { defineClub } from "@/lib/clubs/club"

import ambiance from "./ambiance.json"
import brand from "./brand.json"
import content from "./content.json"
import layout from "./layout.json"
import assets from "./public/lightmaps.json"

/** ${name}, ${city}: demo generated by VYRA Studio, see README.md. */
export default defineClub({ content, layout, brand, ambiance, assets })
`
}
