import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs"
import os from "node:os"
import path from "node:path"

import sharp from "sharp"

import type { RunContext } from "@studio/jobs/context"
import { registerClub } from "@studio/lib/registry-file"
import { validateClub } from "@studio/lib/validate"

/** What leaves the machine: the club as the site reads it. Never scene.json, build/ or private/. */
const PUBLISHED = [
  "content.json",
  "layout.json",
  "brand.json",
  "ambiance.json",
  "index.ts",
  "README.md",
  "public",
  "reference",
]

/**
 * Publication: a branch from origin/main with the club's folder, its registry line and its
 * captures, then a pull request — never a push to main. Works in a temporary git worktree so
 * the Studio's own branch (local only) never leaves the machine. `dryRun` stops before pushing.
 */
export async function publish(ctx: RunContext): Promise<void> {
  const p = ctx.paths
  const v = validateClub(ctx.slug)
  if (!v.ok) throw new Error("Spécification invalide")
  if (!existsSync(p.files.assets))
    throw new Error("Pas de bundle web : lancer l'éclairage précalculé")
  const captures = existsSync(p.captures)
    ? readdirSync(p.captures).filter((f) => f.endsWith(".png"))
    : []
  if (!captures.length) throw new Error("Pas de captures : lancer l'aperçu")
  const content = JSON.parse(readFileSync(p.files.content, "utf8")) as {
    club: { name: string; city: string }
    event: { slug: string }
  }
  const issue =
    typeof ctx.options.issue === "string" && /^VYR-\d+$/.test(ctx.options.issue)
      ? ctx.options.issue
      : null
  const branch = issue ? `feat/${issue}-${ctx.slug}` : `feat/club-${ctx.slug}`
  const tree = path.join(os.tmpdir(), "vyra-publish", ctx.slug)

  await ctx.phase("Branche depuis origin/main", async () => {
    await ctx.exec("git", ["fetch", "origin", "main"])
    // a club folder only makes sense once main reads clubs/ (VYR-58)
    await ctx.exec("git", ["cat-file", "-e", "origin/main:clubs/registry.ts"]).catch(() => {
      throw new Error(
        "origin/main ne lit pas encore clubs/ : merger d'abord la PR « un dossier par club » (VYR-58)",
      )
    })
    if (existsSync(tree))
      await ctx.exec("git", ["worktree", "remove", "--force", tree]).catch(() => undefined)
    rmSync(tree, { recursive: true, force: true })
    mkdirSync(path.dirname(tree), { recursive: true })
    await ctx.exec("git", ["worktree", "add", "-B", branch, tree, "origin/main"])
  })

  await ctx.phase("Dossier du club, registre et captures", async () => {
    const dest = path.join(tree, "clubs", ctx.slug)
    mkdirSync(dest, { recursive: true })
    for (const entry of PUBLISHED) {
      const src = path.join(p.dir, entry)
      if (existsSync(src)) cpSync(src, path.join(dest, entry), { recursive: true })
    }
    const registry = path.join(tree, "clubs", "registry.ts")
    writeFileSync(registry, registerClub(ctx.slug, readFileSync(registry, "utf8")))
    const media = path.join(tree, "docs", "media", "clubs", ctx.slug)
    mkdirSync(media, { recursive: true })
    for (const file of captures) {
      await sharp(path.join(p.captures, file))
        .resize({ width: 1440, withoutEnlargement: true })
        .jpeg({ quality: 80, mozjpeg: true })
        .toFile(path.join(media, file.replace(/\.png$/, ".jpg")))
    }
  })

  const title = `feat(clubs): ${content.club.name} demo (${content.club.city})`
  await ctx.phase("Commit", async () => {
    await ctx.exec("git", ["add", "-A"], { cwd: tree })
    await ctx.exec(
      "git",
      [
        "commit",
        "-q",
        "-m",
        title,
        "-m",
        `Demo generated by VYRA Studio: plan, offers and prices are provisional, not validated by the club.`,
      ],
      {
        cwd: tree,
      },
    )
  })

  if (ctx.options.dryRun) {
    ctx.log(`Essai à blanc : branche ${branch} prête dans ${tree}, rien n'a été poussé.`)
    ctx.setResult({ branch, dryRun: true, worktree: tree })
    return
  }

  const prUrl = await ctx.phase("Push et pull request", async () => {
    await ctx.exec("git", ["push", "-u", "origin", branch], { cwd: tree })
    const raw = `https://github.com/Miche1-Pierre/vyra-dice/blob/${branch}/docs/media/clubs/${ctx.slug}`
    const body = [
      issue ? `## Linear\n\nCloses ${issue}\n` : "",
      `## Quoi\n\nDémo de **${content.club.name}** (${content.club.city}) générée par VYRA Studio : \`/${ctx.slug}/${content.event.slug}\`.`,
      "Plan, tables, capacités et prix **provisoires, non validés par le club** ; mode démo, aucune demande transmise.",
      `\n## Captures\n\n${captures.map((f) => `![${f}](${raw}/${f.replace(/\.png$/, ".jpg")}?raw=true)`).join("\n")}`,
      `\n## À valider avec le club\n\nVoir \`clubs/${ctx.slug}/README.md\`.`,
    ].join("\n")
    const out = await ctx.exec(
      "gh",
      ["pr", "create", "--base", "main", "--head", branch, "--title", title, "--body", body],
      { cwd: tree },
    )
    return (
      out
        .trim()
        .split(/\s+/)
        .find((w) => w.startsWith("https://")) ?? out.trim()
    )
  })
  await ctx.exec("git", ["worktree", "remove", "--force", tree]).catch(() => undefined)
  writeFileSync(p.publish, JSON.stringify({ branch, prUrl, at: new Date().toISOString() }, null, 2))
  ctx.setResult({ branch, prUrl })
}
