import { clubs, drafts } from "@clubs/registry"
import type { ClubDefinition } from "@/lib/clubs/club"
import type { VenueContent } from "@/lib/schema"

/*
 * Server-side access to the registered clubs (`clubs/registry.ts`). Client components get the
 * one club they show from the venue page: importing this module would bundle every club.
 */

/**
 * Drafts — clubs generated by VYRA Studio, not published yet — are served in development, in
 * tests and on Vercel previews, where the team reviews them. Never on the live site: a
 * production build only serves them when Vercel says it is a preview, so a build that does not
 * know where it runs leaves them out.
 */
export function servesDrafts(
  env: { NODE_ENV?: string; VERCEL_ENV?: string } = process.env,
): boolean {
  return env.NODE_ENV !== "production" || env.VERCEL_ENV === "preview"
}

const seen = new Set<string>()
for (const club of [...clubs, ...drafts]) {
  if (seen.has(club.slug)) {
    throw new Error(`Club "${club.slug}" is registered twice in clubs/registry.ts`)
  }
  seen.add(club.slug)
}

const served: readonly ClubDefinition[] = servesDrafts() ? [...clubs, ...drafts] : clubs
const bySlug = new Map(served.map((club) => [club.slug, club]))
const draftSlugs = new Set(drafts.map((club) => club.slug))

export function listClubs(): readonly ClubDefinition[] {
  return served
}

export function getClub(slug: string): ClubDefinition | null {
  return bySlug.get(slug) ?? null
}

/** A club generated by the Studio and not published yet (served off the live site only). */
export function isDraft(slug: string): boolean {
  return draftSlugs.has(slug)
}

/** The night on sale at a club, if the event slug matches. */
export function getVenueContent(club: string, event: string): VenueContent | null {
  const content = getClub(club)?.content
  return content && content.event.slug === event ? content : null
}

/** Route params of every venue night, for `generateStaticParams`. */
export function listVenues(): { club: string; event: string }[] {
  return served.map((club) => ({ club: club.slug, event: club.content.event.slug }))
}
