import type { ClubDefinition } from "@/lib/clubs/club"

import lumenClub from "./lumen-club"
import naho from "./naho"

/**
 * Every club the app serves at `/<slug>/<event>`. Adding a club = creating its folder and adding
 * it here, nowhere else (docs/clubs.md). Each folder validates its own files when it loads.
 */
export const clubs: readonly ClubDefinition[] = [naho]

/**
 * Clubs generated by VYRA Studio and not published yet: served locally and on Vercel previews,
 * never on the live site (src/lib/clubs/registry.ts). Publishing = moving a club to `clubs`.
 */
export const drafts: readonly ClubDefinition[] = [lumenClub]
